### ISSUE TITLE
获取数据集

### ISSUE THREAD

**Issue by hoolizou** [dfew-dataset/dfew-dataset.github.io#1]
您好！
请问，能通过什么途径获取到数据集！
谢谢！

**Comment by jiangxingxun** [comment]
> 您好！
> 请问，能通过什么途径获取到数据集！
> 谢谢！

按照 https://dfew-dataset.github.io/download.html 的提示，给作者发邮件就可以啦

**Comment by hoolizou** [comment]
> > 您好！
> > 请问，能通过什么途径获取到数据集！
> > 谢谢！
> 
> 按照 https://dfew-dataset.github.io/download.html 的提示，给作者发邮件就可以啦

您好！
通过html解析download.html后，我看到了申请的要求；
不过，其中一点提及到：This database is publicly available. It is free for professors and researcher scientists affiliated to a University.
请问，能否以学生（研究生）身份申请此数据集。

**Comment by jiangxingxun** [comment]
> > > 您好！
> > > 请问，能通过什么途径获取到数据集！
> > > 谢谢！
> > 
> > 
> > 按照 https://dfew-dataset.github.io/download.html 的提示，给作者发邮件就可以啦
> 
> 您好！
> 通过html解析download.html后，我看到了申请的要求；
> 不过，其中一点提及到：This database is publicly available. It is free for professors and researcher scientists affiliated to a University.
> 请问，能否以学生（研究生）身份申请此数据集。

可以
